deployment:
    tasks:
        - export DEPLOYPATH=/home/eal236bnt9pe/admin/

        # Navigate to repo folder (Git repo root)
        - cd $DEPLOYPATH

        # Install Node dependencies
        - npm install

        # Build the project
        - npm run build

        # Clean old files (except .git and .htaccess)
        - /bin/find $DEPLOYPATH -mindepth 1 -maxdepth 1 ! -name '.git' ! -name '.htaccess' -exec rm -rf {} +

        # Copy build output into document root
        - /bin/cp -R dist/* $DEPLOYPATH
